GENERAL:
  name_exp: sr_model
  checkpoints_dir: ./sr_checkpoints
  model_dir: ./sr_model
  log_dir: ./sr_logs
  default_dtype: float32
  seed: 100

ARCHITECTURE:
  activation_fn: silu
  r_max: 6.
  r_max_lr: 0.01
  cutoff_fn: phys
  degrees: [1,2,3,4]
  dispersion_energy_bool: false
  dispersion_energy_scale: 0.
  dispersion_energy_cutoff_lr_damping: 0.
  electrostatic_energy_bool: false
  electrostatic_energy_scale: 0.
  energy_activation_fn: silu
  energy_learn_atomic_type_scales: true
  energy_learn_atomic_type_shifts: true
  energy_regression_dim: 128
  input_convention: positions
  layer_normalization_1: true
  layer_normalization_2: true
  message_normalization: avg_num_neighbors
  num_features: 128
  num_heads: 4
  num_layers: 3
  num_radial_basis_fn: 32
  qk_non_linearity: identity
  radial_basis_fn: bernstein
  residual_mlp_1: true
  residual_mlp_2: false
  use_charge_embed: true
  use_spin_embed: true
  zbl_repulsion_bool: true
  neighborlist_format_lr: none
  compute_avg_num_neighbors: True

TRAINING:
  batch_size: 5
  valid_batch_size: 5
  weight_decay: 0.
  lr: 0.
  optimizer: adam
  amsgrad: True
  scheduler: exponential_decay 
  lr_scheduler_gamma: 0.85
  energy_weight: 0.000001
  forces_weight: 1000.
  eval_interval: 1
  num_epochs: 5
  path_to_train_data: ./md17_ethanol_small.xyz
  valid_ratio: 0.1
  clip_grad: 10.0
  neighbors_lr_cutoff: 0.
  patience: 50


MISC:
  device: cpu
  distributed: false  # set true for multi-GPU DDP training
  # launcher: torchrun  # slurm | torchrun | mpi (required when distributed: true)
