ARCHITECTURE:
  activation_fn: silu
  atomic_type_shifts: null
  avg_num_neighbors: 13.168995780096482
  c6_ratios_bool: false
  cutoff_fn: phys
  degrees:
  - 1
  - 2
  - 3
  - 4
  device: cpu
  dispersion_energy_bool: true
  dispersion_energy_cutoff_lr_damping: null
  dispersion_energy_scale: 1.2
  dtype: float32
  electrostatic_energy_bool: true
  electrostatic_energy_scale: 4.0
  energy_activation_fn: silu
  energy_learn_atomic_type_scales: true
  energy_learn_atomic_type_shifts: true
  energy_regression_dim: 128
  final_layer_bias: true
  input_convention: positions
  layer_normalization_1: true
  layer_normalization_2: true
  layers_behave_like_identity_fn_at_init: false
  legacy_dispersion_bool: true
  message_normalization: avg_num_neighbors
  nhl_repulsion_bool: false
  num_elements: 118
  num_features: 128
  num_features_head: 32
  num_heads: 4
  num_layers: 3
  num_radial_basis_fn: 32
  num_theory_levels: 1
  output_is_zero_at_init: false
  pme_dispersion_mesh_spacing: null
  pme_dispersion_smearing: null
  pme_mesh_spacing: null
  pme_smearing: null
  qk_non_linearity: identity
  qk_norm: false
  r_max: 4.5
  r_max_lr: null
  radial_basis_fn: bernstein
  residual_mlp_1: true
  residual_mlp_2: false
  trainable_rbf: false
  use_charge_embed: true
  use_pme: false
  use_pme_dispersion: false
  use_residual_scalars: false
  use_rms_norm: false
  use_simple_hirshfeld: false
  use_spin_embed: true
  zbl_repulsion_bool: true
